find_package(rclcpp REQUIRED)
find_package(rclcpp_lifecycle REQUIRED)
find_package(std_srvs REQUIRED)

ament_add_gtest(simple_localizer_tests simple_localizer_tests.cpp)
target_link_libraries(simple_localizer_tests
  ${PROJECT_NAME}
  rclcpp::rclcpp
  rclcpp_lifecycle::rclcpp_lifecycle
  ${std_srvs_TARGETS}
)

ament_add_gtest(simple_localizer_reconfigure_tests simple_localizer_reconfigure_tests.cpp)
target_link_libraries(simple_localizer_reconfigure_tests
  ${PROJECT_NAME}
  rclcpp::rclcpp
  rclcpp_lifecycle::rclcpp_lifecycle
)

ament_add_gtest(simple_localizer_last_known_pose_tests simple_localizer_last_known_pose_tests.cpp)
target_link_libraries(simple_localizer_last_known_pose_tests
  ${PROJECT_NAME}
  rclcpp::rclcpp
)

ament_add_gtest(simple_localizer_min_height_tests simple_localizer_min_height_tests.cpp)
target_link_libraries(simple_localizer_min_height_tests ${PROJECT_NAME})
